### ISSUE TITLE
Can't rebuild nslog on windows

### ISSUE THREAD

**Issue by joeferraro** [electronjs/electron-rebuild#15]
I'm running `electron-rebuild` on an Appveyor machine and cannot rebuild the `nslog` module. I've tried a seemingly endless combination of `node`, `npm`, `python`, and `visual studio` versions to no avail. Here's the log, any ideas?

```
C:\projects\my-app\app\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\projects\my-app\app\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
 
npm WARN prefer global coffee-script@1.9.3 should be installed with -g
gyp ERR! clean error 
gyp ERR! stack Error: EPERM, unlink 'C:\projects\my-app\app\node_modules\nslog\build\Release\nslog.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\projects\\my-app\\app\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\my-app\app\node_modules\nslog
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\projects\\mavensmate-app\\app\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--target=0.30.2" "--arch=ia32"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.1
npm ERR! code ELIFECYCLE
npm ERR! nslog@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\my-app\app\node_modules\npm-debug.log
 
Process exited with code: 1
```

Please note `npm install nslog` works fine.

**Comment by paulcbetts** [comment]
> gyp ERR! stack Error: EPERM, unlink 'C:\projects\myapp\app\node_modules\nslog\build\Release\nslog.node' gyp ERR! stack     at Error (native)

This means you're getting an Access Denied while trying to delete the old nslog.node, either because some other module has it loaded, or you've somehow built it to a folder you don't have full permissions to?

**Comment by joeferraro** [comment]
> either because some other module has it loaded

curious how this would happen in a straightforward build script (`npm install && .\node_modules\.bin\electron-rebuild`). is this common?

> or you've somehow built it to a folder you don't have full permissions to

I'm not a Windows developer by trade, but this documentation seems to imply access should not be an issue on Appveyor

![services_and_databases_-_appveyor](https://cloud.githubusercontent.com/assets/54157/9061912/dd76ca1a-3a8c-11e5-9999-51b004c0fbf0.png)


Anyway, I'll keep digging, any add'l insight would be appreciated. Cheers.

**Comment by paulcbetts** [comment]
This _might_ be Antivirus in action? If that machine is slow enough, the file would be locked though I'd expect that bug to be transient then. Try adding a delay between npm install and electron-rebuild

**Comment by joeferraro** [comment]
> Try adding a delay between npm install and electron-rebuild

tried `timeout 5` without luck :-1: 

will keep trying things

**Comment by s-a** [comment]
@joeferraro  I success fully build nslog on windows and faced also some curious behaviors. 
I tried all ways described at https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md.    
The node gyp way works best for me, but I figured out that I had to use fresh clones from github to compile. I am not really happy with that because this does not really respect the current version and installs always the latest.


How ever I bundled this practical knowledge into https://github.com/s-a/electron-recompile which aims to following...

 - give more love to windows 
 - more console log outputs to have a better control
 - manage different version for different v8 versions (different output folders as described at https://github.com/s-a/nmp - inspired by fibers) 


Using it via API from within an electron app it handles all informations like platform and arch automatically.  I wrote an electron app which is doing even this.

You can try this. 

```bash
npm install -g iron-node
npm install nslog
iron-node --compile
```

@paulcbetts Do you think we can improve electron-rebuild with these aspects so that I can use it in favor of electron-recompile? I really like to avoid a stand-alone solution.

**Comment by paulcbetts** [comment]
> give more love to windows

What do you mean by this?

**Comment by s-a** [comment]
I mean it should work better on windows. I'm sorry this is not meant evil. I would like to use electron-rebuild. This is the reason I wrote here.

**Comment by s-a** [comment]
Btw: Do you know where I can find a list of operating system s supported by electron? A user reporter he cannot install on freeBSD.

**Comment by paulcbetts** [comment]
> I mean it should work better on windows. I'm sorry this is not meant evil. I would like to use electron-rebuild. This is the reason I wrote here.

I know that, but what do you mean by that? I use it every day to build on Windows

**Comment by s-a** [comment]
Hmm, then I said nothing :smile: 
Maybe I mix some things up there. I had problems compiling fibers and bcrypt. I woul d not focus in this. Just thought you guys love osx have not so much attention for Windows. My fault.

**Comment by rahatarmanahmed** [comment]
I'm having the same issue on iojs v3.0.0. Here's a [log](https://gist.github.com/rahatarmanahmed/fa8a15fb9a39443853ab). It works fine if I revert to iojs v2.5.0, though.

**Comment by kpko** [comment]
I might have encountered a similar problem in #18.

**Comment by paulcbetts** [comment]
Any issues involving io.js are most likely fixed in electron-rebuild 1.0.0, reopen if anyone sees it

**Comment by tobico** [comment]
I'm seeing what appears to be exactly the same issue with electron-rebuild 1.1.3, under Windows 10:

```
PS C:\Users\me\Documents\Code\songstress> .\node_modules\.bin\electron-rebuild                                                                                                                                                                            
                                                                                                                                                                                                                                                          
> sqlite3@3.1.1 install C:\Users\me\Documents\Code\songstress\node_modules\sqlite3                                                                                                                                                                        
> node-pre-gyp install --fallback-to-build                                                                                                                                                                                                                
                                                                                                                                                                                                                                                          
[sqlite3] Success: "C:\Users\me\Documents\Code\songstress\node_modules\sqlite3\lib\binding\electron-v0.36-win32-x64\node_sqlite3.node" already installed                                                                                                  
Pass --update-binary to reinstall or --build-from-source to recompile                                                                                                                                                                                     
                                                                                                                                                                                                                                                          
> electron-prebuilt@0.36.7 postinstall C:\Users\me\Documents\Code\songstress\node_modules\electron-prebuilt                                                                                                                                               
> node install.js                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
> nslog@3.0.0 install C:\Users\me\Documents\Code\songstress\node_modules\nslog                                                                                                                                                                            
> node-gyp rebuild                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
C:\Users\me\Documents\Code\songstress\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\me\Documents\Code\songstress\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild 
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
gyp ERR! clean error                                                                                                                                                                                                                                      
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\me\Documents\Code\songstress\node_modules\nslog\build\Release\nslog.node'                                                                                                          
gyp ERR! stack     at Error (native)                                                                                                                                                                                                                      
gyp ERR! System Windows_NT 10.0.10586                                                                                                                                                                                                                     
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\Documents\\Code\\songstress\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"                                                                                
gyp ERR! cwd C:\Users\me\Documents\Code\songstress\node_modules\nslog                                                                                                                                                                                     
gyp ERR! node -v v4.2.6                                                                                                                                                                                                                                   
gyp ERR! node-gyp -v v3.2.1                                                                                                                                                                                                                               
gyp ERR! not ok                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                          
npm ERR! Windows_NT 10.0.10586                                                                                                                                                                                                                            
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\Documents\\Code\\songstress\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=0.36.7" "--arch=x64"                                                        
npm ERR! node v4.2.6                                                                                                                                                                                                                                      
npm ERR! npm  v3.7.2                                                                                                                                                                                                                                      
npm ERR! code ELIFECYCLE                                                                                                                                                                                                                                  
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`                                                                                                                                                                                                          
npm ERR! Exit status 1                                                                                                                                                                                                                                    
npm ERR!                                                                                                                                                                                                                                                  
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.                                                                                                                                                                                     
npm ERR! Make sure you have the latest version of node.js and npm installed.                                                                                                                                                                              
npm ERR! If you do, this is most likely a problem with the nslog package,                                                                                                                                                                                 
npm ERR! not with npm itself.                                                                                                                                                                                                                             
npm ERR! Tell the author that this fails on your system:                                                                                                                                                                                                  
npm ERR!     node-gyp rebuild                                                                                                                                                                                                                             
npm ERR! You can get information on how to open an issue for this project with:                                                                                                                                                                           
npm ERR!     npm bugs nslog                                                                                                                                                                                                                               
npm ERR! Or if that isn't available, you can get their info via:                                                                                                                                                                                          
npm ERR!     npm owner ls nslog                                                                                                                                                                                                                           
npm ERR! There is likely additional logging output above.                                                                                                                                                                                                 
                                                                                                                                                                                                                                                          
npm ERR! Please include the following file with any support request:                                                                                                                                                                                      
npm ERR!     C:\Users\me\Documents\Code\songstress\node_modules\npm-debug.log                                                                                                                                                                             
                                                                                                                                                                                                                                                          
Process exited with code: 1                                                                                                                                                                                                                               
Error: Process exited with code: 1                                                                                                                                                                                                                        
    at ChildProcess.<anonymous> (C:\Users\me\Documents\Code\songstress\node_modules\electron-rebuild\lib\spawn.js:55:26)                                                                                                                                  
    at emitTwo (events.js:87:13)                                                                                                                                                                                                                          
    at ChildProcess.emit (events.js:172:7)                                                                                                                                                                                                                
    at maybeClose (internal/child_process.js:821:16)                                                                                                                                                                                                      
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)                                                                                                                                                                              
```

I've tried deleting my node_modules directory and reinstalling, clearing the npm cache, and running the command in an admin powershell, to no effect.

**Comment by simoneb** [comment]
I didn't manage to build it on Windows but what I did is, because nslog doesn't seem to be a runtime dependency but rather a development dependency, to split my app in two package.json files, so that I only need to electron-rebuild the runtime one, and avoid the nslog issue altogether.

**Comment by tobico** [comment]
Thanks @simoneb, I got there in the end, using command line arguments:

```
electron-rebuild -w sqlite3 -p
```

I feel like these are probably useful enough to warrant mentioning them in the Readme. I can write up some notes in a PR if that helps.

**Comment by tarikakyol** [comment]
try installing dependencies via [http://chocolatey.org](chocolatey)

`choco install python2`
`choco install visualstudioexpress2013windowsdesktop`

**Comment by xiangkaiy** [comment]
Thanks to tobico. I wonder where to find the parameter -w and -p.

**Comment by delebash** [comment]
@tobico  Thanks that worked for me.  I didn't even think of looking at help with the error I was getting, thanks.

@xiangkaiy  use -h
./node_modules/.bin/electron-rebuild -h

Also in source https://github.com/electron/electron-rebuild/blob/master/src/cli.js

**Comment by iarovyi** [comment]
-h did not help
`.D:\PROJECTS\angular2-seed-advanced>.\node_modules\.bin\electron-rebuild.cmd -h
module.js:457
    throw err;
    ^

Error: Cannot find module 'D:\PROJECTS\angular2-seed-advanced\node_modules\electron-rebuild\lib\cli.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`

**Comment by delebash** [comment]
@iarovyi  The -h is for "help" which shows a list of switches.  The actual command is `./node_modules/.bin/electron-rebuild -w (insert your module) -p`   In my case to rebuild leveldown  I use `./node_modules/.bin/electron-rebuild -w leveldown -p `

I think the above error is because you are prefixing the command with `node `at least that is the error I get if I try the below command
`node ./node_modules/.bin/electron-rebuild -w leveldown -p`

Don't try to run it with node  just paste this into your terminal as is
` ./node_modules/.bin/electron-rebuild -w leveldown -p `
