### ISSUE TITLE
edge-atom-shell not installing due to a linker error.

### ISSUE THREAD

**Issue by EdAyers** [electronjs/electron-rebuild#16]
Hi, I can't find a better place to post this issue so I'm going with here because the error seems to be to do with the rebuild process. I hope this is a replicable issue that others may have but if it's just me being silly I'm sorry.

I'm trying to get electron and edge.js to work together. I'm using windows 10. Here are my versions of node things;
```
{ npm: '2.7.4',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }
```
If I make a new directory and run `npm install edge-atom-shell` I get the following output. I get the same output if I call `npm install electron-prebuilt` first and then `npm install edge-atom-shell`.
```
PS E:\Projects\electron4> npm install edge-atom-shell
/
> edge-atom-shell@0.10.4 install E:\Projects\electron4\node_modules\edge-atom-shell
> node-gyp rebuild


E:\Projects\electron4\node_modules\edge-atom-shell>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\node
js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  edge.cpp
  utils.cpp
  clrfunc.cpp
  clrfuncinvokecontext.cpp
  nodejsfunc.cpp
  nodejsfuncinvokecontext.cpp
  persistentdisposecontext.cpp
  clrfuncreflectionwrap.cpp
  v8synchronizationcontext.cpp
  clractioncontext.cpp
LINK : fatal error LNK1104: cannot open file 'MSVCMRT.lib' [E:\Projects\electron4\node_modules\edge-atom-shell\build\edge.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\electron4\node_modules\edge-atom-shell
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "edge-atom-shell"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! edge-atom-shell@0.10.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edge-atom-shell@0.10.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the edge-atom-shell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
LINK : fatal error LNK1104: cannot open file 'MSVCMRT.lib' 
npm ERR! You can get their info via:
npm ERR!     npm owner ls edge-atom-shell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projects\electron4\npm-debug.log
```
The important thing seems to be that I'm getting a linker error `LINK : fatal error LNK1104: cannot open file 'MSVCMRT.lib' [E:\Projects\electron4\node_modules\edge-atom-shell\build\edge.vcxproj]` What do I need to do to get this to work?

Here is [npm-debug.log](E:\Projects\electron4https://gist.github.com/EdAyers/48cf3e74385a7ca18735). It's pretty much meaningless to me so I've probably missed something trivial. Is there something I need to globally install before this will work?

**Comment by paulcbetts** [comment]
You can't use VS2015 to build anything Electron right now, install VS2013 and set the environment variable `GYP_MSVS_VERSION=2013`

**Comment by vasumahesh1** [comment]
@paulcbetts I have the variable set GYP_MSVS_VERSION to 2013. Have both VS 2015 and VS 2013. But electron-rebuild seems to be using 2015 version.

I am trying to rebuild [pdfium](https://github.com/tojocky/node-pdfium). Here is the log I am getting on rebuild:

```
PS> Get-ChildItem Env:GYP_MSVS_VERSION

Name                           Value
----                           -----
GYP_MSVS_VERSION               2013

.\node_modules\.bin\electron-rebuild .

  color.cpp
  console.cpp
  Consts.cpp
  Document.cpp
  event.cpp
  Field.cpp
  global.cpp
  Icon.cpp
  JS_Context.cpp
  JS_EventHandler.cpp
  JS_GlobalData.cpp
  JS_Object.cpp
  JS_Runtime.cpp
  JS_Value.cpp
  PublicMethods.cpp
  report.cpp
  resource.cpp
  util.cpp
..\..\..\third_party\pdfium\fpdfsdk\src\javascript\JS_Runtime.cpp(103): error C2660: 'v8::Isolate::New' : function does
not take 0 arguments [P:\tempProject\node_modules\pdfium\build\third_party\pdfium\javascript
vcxproj]
..\..\..\third_party\pdfium\fpdfsdk\src\javascript\PublicMethods.cpp(229): warning C4244: 'argument' : conversion from
__int64' to 'FX_STRSIZE', possible loss of data [P:\tempProject\node_modules\pdfium\build\th
rd_party\pdfium\javascript.vcxproj]
..\..\..\third_party\pdfium\fpdfsdk\src\javascript\PublicMethods.cpp(250): warning C4244: 'argument' : conversion from
__int64' to 'FX_STRSIZE', possible loss of data [P:\tempProject\node_modules\pdfium\build\th
rd_party\pdfium\javascript.vcxproj]
  fxjs_v8.cpp
  win_delay_load_hook.c
  jsapi.vcxproj -> P:\tempProject\node_modules\pdfium\build\Release\\jsapi.lib
  PWL_Button.cpp
  PWL_Caret.cpp
  PWL_ComboBox.cpp
  PWL_Edit.cpp
  PWL_EditCtrl.cpp
  PWL_FontMap.cpp
  PWL_Icon.cpp
  PWL_IconList.cpp
  PWL_Label.cpp
  PWL_ListBox.cpp
  PWL_ListCtrl.cpp
  PWL_Note.cpp
  PWL_ScrollBar.cpp
  PWL_Signature.cpp
  PWL_SpecialButton.cpp
  PWL_Utils.cpp
  PWL_Wnd.cpp
  win_delay_load_hook.c
  pdfwindow.vcxproj -> P:\tempProject\node_modules\pdfium\build\Release\\pdfwindow.lib

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (P:\tempProject\node_modules\electron-rebuild\node
modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "P:\\tempProject\\node_modules\\electron-rebuild\\node_modules\\n
m\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd P:\tempProject\node_modules\pdfium
gyp ERR! node -v v0.12.10
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
```

`C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` Seems to be using 14.0 ? Shouldn't VS2013 use 12.0 ? I have two folders in MSBuild one is 14.0 other is 12.0

Pretty sure I have VS 2013 Installed correctly as node-pdfium [requires VS2013](https://github.com/tojocky/node-pdfium/issues/2#issuecomment-96797377) for a stable build and I was facing a lot of issues with VS2015, Yesterday downloaded the Community edition of 2013 and I was able to npm install it.

Any help would be awesome.. Been stuck on this issue for a long time :(
