### ISSUE TITLE
Error building zmq package on Windows

### ISSUE THREAD

**Issue by kpko** [electronjs/electron-rebuild#18]
Hi,

I'm trying to use electron shell with zmq.

When I try to use zmq in my electron shell app after installing via "npm install zmq", I get an error:

```
C:\Projects\snom-client>node_modules\.bin\electron.cmd .
[62752:0825/141645:INFO:CONSOLE(0)] App threw an error when running [Error: A dynamic link library (DLL) i
nitialization routine failed.
C:\Projects\snom-client\node_modules\zmq\build\Release\zmq.node]
```

After reading trough the docs on native modules (http://electron.atom.io/docs/v0.31.0/tutorial/using-native-node-modules/), I tried the "easy" method to get electron running with the native zmq module via electron-rebuild. This leads to some cryptic warnings and errors:

```
C:\Projects\snom-client>node_modules\.bin\electron-rebuild.cmd

> zmq@2.12.0 install C:\Projects\snom-client\node_modules\zmq
> node-gyp rebuild


C:\Projects\snom-client\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Projects\snom-client
\node_modules\electron-rebuild\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node  rebuild )
  binding.cc
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsur
eLocal(v8::Local<T>)': function template has already been defined [C:\Projects\snom-client\node_modules\zm
q\build\zmq.vcxproj]
  C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(256): note: see declaration of '_NanEnsu
reLocal'
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol t
o the left of a '::' must be a type [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(661): error C2039: 'FreeCallback': is not
a member of 'node' [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
  C:\Projects\snom-client\node_modules\electron-rebuild\lib\headers\.node-gyp\0.31.0\src\node_object_wrap.
h(8): note: see declaration of 'node'
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(661): error C2061: syntax error: identifie
r 'FreeCallback' [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(665): error C2065: 'callback': undeclared
identifier [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(665): error C2065: 'hint': undeclared iden
tifier [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New': no
ne of the 4 overloads could convert all the argument types [C:\Projects\snom-client\node_modules\zmq\build
\zmq.vcxproj]
  C:\Projects\snom-client\node_modules\electron-rebuild\lib\headers\.node-gyp\0.31.0\src\node_buffer.h(50)
: note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
  C:\Projects\snom-client\node_modules\electron-rebuild\lib\headers\.node-gyp\0.31.0\src\node_buffer.h(38)
: note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::e
ncoding)'
  C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(672): note: while trying to match the ar
gument list '(v8::Isolate *, const char *, uint32_t)'
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(676): error C2440: 'return': cannot conver
t from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [C:\Projects\snom-client\node_modules\zmq\b
uild\zmq.vcxproj]
  C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(676): note: No constructor could take th
e source type, or constructor overload resolution was ambiguous
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(683): error C2039: 'Use': is not a member
of 'node::Buffer' [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
  C:\Projects\snom-client\node_modules\electron-rebuild\lib\headers\.node-gyp\0.31.0\src\node_buffer.h(8):
 note: see declaration of 'node::Buffer'
C:\Projects\snom-client\node_modules\zmq\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not f
ound [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(654): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(655): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(656): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(657): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(658): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(659): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(660): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(661): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(662): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(663): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(678): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(679): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(680): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(681): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(682): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(683): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(684): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(685): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(686): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of
data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(687): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [
C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(930): error C2661: 'NanNewBufferHandle': no overloaded function takes 4 arguments [C:\Projec
ts\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(1047): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data [C:\Pro
jects\snom-client\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(1148): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data [C:\Pro
jects\snom-client\node_modules\zmq\build\zmq.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Projects\snom-client\node_modules\electron-rebuild\node_modu
les\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Projects\\snom-client\\node_modules\\electron-rebuild\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\snom-client\node_modules\zmq
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Projects\\snom-client\\node_modules\\electron-rebuild\\node_modules\\npm\\bin\\n
pm-cli.js" "rebuild" "--target=0.31.0" "--arch=x64"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! zmq@2.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.12.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\snom-client\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Projects\snom-client\node_modules\electron-rebuild\lib\spawn.js:53:26)

    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

C:\Projects\snom-client>
```

This should not be a problem with the zmq package, because if I try to use it without the electron shell it works fine.

**Comment by paulcbetts** [comment]
You're trying to build with VS2015, Install VS2013 Update 4, then set the `GYP_MSVS_VERSION` environment variable to `2013`

**Comment by kpko** [comment]
Hi,

thank you very much! The zmq native module gets successfully compiled now with the help of your advise to use VS2013.

Still I have an error later in the chain.

```
C:\Projects\snom-client>node_modules\.bin\electron-rebuild

> zmq@2.13.0 install C:\Projects\snom-client\node_modules\zmq
> node-gyp rebuild


C:\Projects\snom-client\node_modules\zmq>if not defined npm_config_node_gyp (nod
e "C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
ele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
  binding.cc
..\binding.cc(642): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(643): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(644): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(645): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(646): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(647): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(648): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(649): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(650): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(651): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(665): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(666): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(667): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(668): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(669): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(670): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(671): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(672): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
..\binding.cc(673): warning C4244: 'argument' : conversion from 'int64_t' to 'co
nst int', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\
zmq.vcxproj]
..\binding.cc(674): warning C4244: 'argument' : conversion from 'int64_t' to 'in
t', possible loss of data [C:\Projects\snom-client\node_modules\zmq\build\zmq.vc
xproj]
c:\projects\snom-client\node_modules\zmq\node_modules\nan\nan_new.h(208): warnin
g C4244: 'argument' : conversion from 'int64_t' to 'double', possible loss of da
ta [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
          ..\binding.cc(593) : see reference to function template instantiation
'v8::Local<v8::Number> Nan::New<v8::Number,T>(A0)' being compiled
          with
          [
              T=int64_t
  ,            A0=int64_t
          ]
          ..\binding.cc(647) : see reference to function template instantiation
'v8::Local<v8::Value> zmq::Socket::GetSockOpt<int64_t>(int)' being compiled
c:\projects\snom-client\node_modules\zmq\node_modules\nan\nan_new.h(208): warnin
g C4244: 'argument' : conversion from 'uint64_t' to 'double', possible loss of d
ata [C:\Projects\snom-client\node_modules\zmq\build\zmq.vcxproj]
          ..\binding.cc(593) : see reference to function template instantiation
'v8::Local<v8::Number> Nan::New<v8::Number,T>(A0)' being compiled
          with
          [
              T=uint64_t
  ,            A0=uint64_t
          ]
          ..\binding.cc(649) : see reference to function template instantiation
'v8::Local<v8::Value> zmq::Socket::GetSockOpt<uint64_t>(int)' being compiled
  win_delay_load_hook.c
     Creating library C:\Projects\snom-client\node_modules\zmq\build\Release\zmq
.lib and object C:\Projects\snom-client\node_modules\zmq\build\Release\zmq.exp
  Generating code
  Finished generating code
  zmq.vcxproj -> C:\Projects\snom-client\node_modules\zmq\build\Release\\zmq.nod
e

> nslog@2.0.0 install C:\Projects\snom-client\node_modules\electron-rebuild\node
_modules\nslog
> node-gyp rebuild


C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog>if not
defined npm_config_node_gyp (node "C:\Projects\snom-client\node_modules\electron
-rebuild\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
ele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
  main.cc
  nslog_win.cc
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(262): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
: function template has already been defined (..\src\main.cc) [C:\Projects\snom-
client\node_modules\electron-rebuild\node_modules\nslog\build\nslog.vcxproj]
          C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nsl
og\node_modules\nan\nan.h(255) : see declaration of '_NanEnsureLocal'
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(660): error C3083: 'smalloc': the symbol to the left of a '::' m
ust be a type (..\src\main.cc) [C:\Projects\snom-client\node_modules\electron-re
build\node_modules\nslog\build\nslog.vcxproj]
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(660): error C2039: 'FreeCallback' : is not a member of 'node' (.
.\src\main.cc) [C:\Projects\snom-client\node_modules\electron-rebuild\node_modul
es\nslog\build\nslog.vcxproj]
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(660): error C2061: syntax error : identifier 'FreeCallback' (..\
src\main.cc) [C:\Projects\snom-client\node_modules\electron-rebuild\node_modules
\nslog\build\nslog.vcxproj]
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(664): error C2065: 'callback' : undeclared identifier (..\src\ma
in.cc) [C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog
\build\nslog.vcxproj]
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(664): error C2065: 'hint' : undeclared identifier (..\src\main.c
c) [C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\bui
ld\nslog.vcxproj]
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(671): error C2665: 'node::Buffer::New' : none of the 4 overloads
 could convert all the argument types (..\src\main.cc) [C:\Projects\snom-client\
node_modules\electron-rebuild\node_modules\nslog\build\nslog.vcxproj]
          C:\Projects\snom-client\node_modules\electron-rebuild\lib\headers\.nod
e-gyp\0.31.0\src\node_buffer.h(50): could be 'v8::MaybeLocal<v8::Object> node::B
uffer::New(v8::Isolate *,char *,size_t)'
          C:\Projects\snom-client\node_modules\electron-rebuild\lib\headers\.nod
e-gyp\0.31.0\src\node_buffer.h(38): or       'v8::MaybeLocal<v8::Object> node::B
uffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *,
 uint32_t)'
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(675): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local
<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v8::Object>' t
o 'const v8::Local<v8::Object> &' (..\src\main.cc) [C:\Projects\snom-client\node
_modules\electron-rebuild\node_modules\nslog\build\nslog.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8:
:Local<v8::Object>'
          No user-defined-conversion operator available that can perform this co
nversion, or the operator cannot be called
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(682): error C2039: 'Use' : is not a member of 'node::Buffer' (..
\src\main.cc) [C:\Projects\snom-client\node_modules\electron-rebuild\node_module
s\nslog\build\nslog.vcxproj]
C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\node_mo
dules\nan\nan.h(682): error C3861: 'Use': identifier not found (..\src\main.cc)
[C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\nslog\build\
nslog.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Projects\snom-client\node_modules\
electron-rebuild\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Projects\\snom-client\\node_modules\\electron-rebui
ld\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\snom-client\node_modules\electron-rebuild\node_modules\
nslog
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Projects\\snom-client\\node_modules\\electron-rebuild\
\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--target=0.31.0" "--arch=x64"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! nslog@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\snom-client\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Projects\snom-client\node_modules\electron-r
ebuild\lib\spawn.js:53:26)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

This could correlate with #15 imho because it fails on building nslog.

**Comment by paulcbetts** [comment]
This is a zmq bug, they need to fix their code to be compatible with newer versions of io.js

**Comment by kpko** [comment]
This one is a different error though after compiling zmq. 

If I "npm uninstall zmq" and "npm install nslog" separately, I get the error above when I use electron-rebuild on my project with nslog and without zmq. But yes, I think this is more a nslog problem than an electron-rebuild problem. See https://github.com/atom/node-nslog/issues/8.

Thank you very much!
