### ISSUE TITLE
Gives error for sqlite3 on Ubuntu

### ISSUE THREAD

**Issue by destan** [electronjs/electron-rebuild#21]
Electron version: v0.31.2
Nodejs version: v0.12.7

Steps to reproduce:

* Clone https://github.com/szwacz/electron-boilerplate
* Add sequelizejs with sqlite3 and try to add example usage from http://docs.sequelizejs.com/en/latest/ page.
* it won't work due to ABI mismatch
* Then install `electron-rebuild` and run it via `./node_modules/.bin/electron-rebuild`

gives following error:

```
> sqlite3@3.0.10 install /home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.30.6

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.6
node-pre-gyp ERR! stack     at get_runtime_abi (/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Linux 3.13.0-62-generic
node-pre-gyp ERR! command "node" "/home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/destan/development/workspace/web/electron-boilerplate/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
```

it somehow reports the node version as `0.30.6`

If I go to `node_modules/node-pre-gyp/lib/util/versioning.js:53` and hardcode `target_version = '0.12.7'` the error vanishes.

**Comment by paulcbetts** [comment]
https://github.com/mapbox/node-pre-gyp/issues/166

**Comment by destan** [comment]
@paulcbetts The link is all about giving an error or not. In the link I couldn't see anything about wrong version reporting, why is my node version seems `0.30.6` when running `electron-boilerplate`?

Maybe I didn't understand something, could you please elaborate?

**Comment by paulcbetts** [comment]
> Maybe I didn't understand something, could you please elaborate?

The bug is, instead of attempting to build sqlite from source (which would work), node-pre-gyp just gives up.
