### ISSUE TITLE
Cannot rebuild fsevents

### ISSUE THREAD

**Issue by nlhkh** [electronjs/electron-rebuild#24]
When I have npm modules such as *webpack* or *babel*, I cannot run `electron-rebuild` successfully because it failed on rebuilding *fsevents*, which is a dependency of the other npm modules.

The way I see it, modules such as *fsevents*, or *webpack* do not need rebuild, because they are usually devDependencies. So I think there should be an option to ignore some npm modules.

**Comment by nlhkh** [comment]
The error message I got is

```
> fsevents@1.0.0 install /Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.33.3

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.33.3
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:452:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/khanguyen/.nvm/versions/node/v4.1.1/bin/node" "/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/khanguyen/.nvm/versions/node/v4.1.1/bin/node" "/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.33.3" "--arch=x64"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.5
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by sheerun** [comment]
I have the same issue

**Comment by paulcbetts** [comment]
Any package right now that switches to node-pre-gyp breaks electron because `--fallback-to-build` doesn't actually work: https://github.com/mapbox/node-pre-gyp/pull/175
