### ISSUE TITLE
v1.0.1 - Mac OS X - Unknown Runtime: 'electron'

### ISSUE THREAD

**Issue by felicienfrancois** [electronjs/electron-rebuild#25]
With version 1.0.1, I get the following error when rebuilding module [fsevents](https://github.com/strongloop/fsevents):
```
Unknown Runtime: 'electron'

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unknown Runtime: 'electron'
node-pre-gyp ERR! stack     at get_runtime_abi (.../fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:60:19)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (.../fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (.../fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (.../fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (.../fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (.../fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" ".../fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd .../fsevents
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok 
```

**Comment by paulcbetts** [comment]
@felicienfrancois Delete your `node_modules` folder and run `npm install` again, this should fix it (and fix the weirdo fsevents problems with node-pre-gyp)

**Comment by felicienfrancois** [comment]
@paulcbetts Your solution does not work with fsevents.

When installing fsevents, i don't get the last node-pre-gyp release but the `0.6.11` which does not support Electron.

It is probably due to the fact that [node-pre-gyp is bundled into fsevents](https://github.com/strongloop/fsevents/blob/master/package.json#L41). the installed version is the bundled one and not the latest.

I get this even on a clean install (no npm cache, nor node_modules).
My temporary hack is to update node-pre-gyp before rebuilding:
```
cd node_modules/fsevents
npm install node-pre-gyp
cd ../..
```

I will make a pull request on fsevents to update the bundled node-pre-gyp
