### ISSUE TITLE
SyntaxError: Unexpected token case

### ISSUE THREAD

**Issue by jgeurts** [electronjs/electron-rebuild#30]
Running `node .\node_modules\.bin\electron-rebuild`, on Windows 10 x64 with node 4.2.1 installed (and got the same error with 4.1.2), gives:

```
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by jgeurts** [comment]
https://github.com/electronjs/electron-rebuild/issues/22#issuecomment-150367087
